### PR TITLE
DEV: Created a learning playground for jared

### PR DESCRIPTION
**Pull request by mrjkey**
learning how things work, only created a new directory for this, nothing on the main files has been edited. 

would like to keep this in the main repo so I don't need to keep one giant branch open

### CODE REVIEW

**Comment by Tris20** [comment]
I can see why that would be helpful, but I can see drift from utils being a pretty big problem here. We'll be duplicating data and when there's updates to utils, how do we ensure this mirrors those updates? The file/data duplication can also make searching the repo for particular things more error prone.

**Comment by mrjkey** [comment]
> I can see why that would be helpful, but I can see drift from utils being a pretty big problem here. We'll be duplicating data and when there's updates to utils, how do we ensure this mirrors those updates? The file/data duplication can also make searching the repo for particular things more error prone.

For keeping things up-to-date / synced :
- This would just be something I would need to manage, because this is a learning folder. If something changed in the main utils then I would need to update my learning files. I wouldn't expect that you also work in this code. 

For data duplication:
- I can reference the original files if you want? I copied over the .csv files so I wouldn't mess with the originals, but I can always delete the copies and reference the originals if that makes more sense

For Searching:
- Ya, the same code would show up in the learning dir, not really a way around that. I figured since this already happens with the drafts directory then it wouldn't be a problem, but if you have a good solution I would be open to it. 

If you would rather, I can keep everything in separate branches

**Comment by Tris20** [comment]
_For keeping things up-to-date / synced :

    This would just be something I would need to manage, because this is a learning folder. If something changed in the main utils then I would need to update my learning files. I wouldn't expect that you also work in this code._

Hmm, the other concern here would be that as it drifts, you might end up getting used to the playground structure etc, instead of the learning the existing one. 

_I can reference the original files if you want? I copied over the .csv files so I wouldn't mess with the originals, but I can always delete the copies and reference the originals if that makes more sense_
I think the decision to keep the data separate here is a good idea. 

_If you would rather, I can keep everything in separate branches_

That might be better. I can see the benefit of having it tied to main, but if it's just for learning then wouldn't it be removed in a few weeks anyway? In that case it would make more sense to be a branch. If you really prefer to have this folder we can do it, but it would also raise the question: do we make a folder for everyone else who is learning the project in main?

**Comment by mrjkey** [comment]
> That might be better. I can see the benefit of having it tied to main, but if it's just for learning then wouldn't it be removed in a few weeks anyway? In that case it would make more sense to be a branch. If you really prefer to have this folder we can do it, but it would also raise the question: do we make a folder for everyone else who is learning the project in main?

Ok, i'll close the PR and just keep things as individual branches.

**Pull request closed without merging**
